name: CI-CD-Pipeline-AWS

permissions:
  id-token: write 
  contents: read
env:
  EB_PACKAGE-S3_BUCKET_NAME: "flask-app-packages1298"
  EB_APPLICATION_NAME: "New-Flask"
  EB_ENVIRONMENT_NAME: "New-Flask-env-1"
  DEPLOY_PACKAGE_NAME: "flask_app_${{github.sha}}.zip"
  AWS_REGION_NAME: "us-east-1"

on:
  push:
    branches:
      - main


jobs:
 
  ci_part:
  
    runs-on: ubuntu-latest

    steps:
      
      - name: Git Clone Repo
        uses: actions/checkout@v1

      - name: Runa a Script
        run: echo "Repo yes Copied!"

      - name: Create a ZIP file
        run: zip -r ${{env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.MY_ROLE}}
          role-session-name: Github
          aws-region: ${{env.AWS_REGION_NAME}}

      - name: Copy ZIP to S3
        run: aws s3 cp ${{env.DEPLOY_PACKAGE_NAME}} s3://${{env.EB_PACKAGE-S3_BUCKET_NAME}}/

      - name: Happy CI Finish
        run: echo "CI Pipline Finished Successfully"
        
        

  cd_part:
  
      runs-on: ubuntu-latest
      needs: [ci_part]

      steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.MY_ROLE}}
          role-session-name: Github
          aws-region: ${{env.AWS_REGION_NAME}}

      - name: Create New Elastic Beanstalk App
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{env.EB_APPLICATION_NAME}} \
          --source-bundle S3Bucket="${{env.EB_PACKAGE-S3_BUCKET_NAME}}",S3Key="${{env.DEPLOY_PACKAGE_NAME}}" \
          --version-label "Ver-${{github.sha}}" \
          --description "CommitSHA-${{github.sha}}"
          
      - name: Deploy New Elastic Beanstalk App
        run: |
            aws elasticbeanstalk update-environment  --environment-name ${{env.EB_ENVIRONMENT_NAME}} \
            --version-label "Ver-${{github.sha}}"

      - name: Great CD Finish
        run: echo "CD Pipline Finished Successfully"
